version: "3.9"
services:
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    restart: always
    ports:
      - "8080:80"
      - "8125:8125/udp"
      - "8126:8126"
      - "2003:2003"
      - "2004:2004"
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    links:
      - graphite
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
  redis:
    image: "redis:6.2.5"
    ports:
      - "6379:6379"
  db:
    image: "postgres:latest"
    command:
      ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: solana # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: solana # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: solana
    volumes:
      - ./db-data/:/var/lib/postgresql/data/:rw
  solana:
    image: ghcr.io/metaplex-foundation/plerkle-test-validator:v1.1.1
    volumes:
      - ./programs:/so/:ro
      - ./ledger:/config:rw
      - ./solana-test-validator-geyser-config:/plugin-config:rw
    environment:
      RUST_LOG: info
      PLUGIN_MESSENGER_CONFIG.messenger_type: "Redis"
      PLUGIN_MESSENGER_CONFIG.connection_config: '{redis_connection_str="redis://redis"}'
    ports:
      - "8900:8900"
      - "8001:8001"
      - "8899:8899"
      - "9900:9900"
    depends_on:
      - redis
      - grafana
      - graphite
volumes:
  grafana_data: {}
  graphite_data: {}
