//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cl_items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub tree: Vec<u8>,
    pub node_idx: i64,
    pub leaf_idx: Option<i64>,
    pub seq: i64,
    pub level: i64,
    pub hash: Vec<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
