[package]
name = "gpl_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plerkle_serialization = "1.5.0"
solana-sdk = "~1.14"
thiserror = "1.0.38"
